name: nile_nini_web
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  fl_chart: ^0.10.0
  flutter_form_builder: ^3.13.0
  font_awesome_flutter: ^8.8.1
  flutter_web_scrollbar: ^0.0.2
  syncfusion_flutter_maps: ^18.2.54-beta
  cloud_firestore: ^0.14.0+1
  firebase_auth: ^0.18.0+1
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.7+4
  image_picker_for_web: ^0.1.0
  flutter_web_image_picker: ^0.0.2




dev_dependencies:
#  # Package used for unit testing
#  test: <latest_version>
#
#  # Package used for Integration testing
#  flutter_driver:
#    sdk: flutter
#    test: any
#
#  #Package used for widget testing
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Google Sans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
    - family: Noto Sans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf

  uses-material-design: true


  assets:
    - images/
    - assets/

