name: nile_nini_web
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  fl_chart: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Google Sans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
    - family: Noto Sans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf

  uses-material-design: true


  assets:
    - images/
